# Use the official Python 3.11 image
FROM python:3.11

# Install dependencies for Chrome and chromedriver
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget \
        curl \
        unzip \
        chromium \
        chromium-driver \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libatk-bridge2.0-0 \
        libnspr4 \
        libnss3 \
        libx11-xcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxi6 \
        libxtst6 \
        xdg-utils && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables for Chrome and chromedriver paths
ENV CHROME_BIN=/usr/bin/chromium
ENV CHROMEDRIVER_PATH=/usr/bin/chromedriver

# Set the working directory
WORKDIR /flaskapp

# Copy the application files
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the application port
EXPOSE 8080

CMD ["python3", "app_selenium.py", "run", "--host=0.0.0.0", "--port=8080"]
